services:
  edutrail.webui:
    image: ${DOCKER_REGISTRY-}edutrailwebui
    build:
      context: .
      dockerfile: src/EduTrail.WebUI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release

  edutrail.db:
    image: postgres:16
    environment:
      POSTGRES_USER: edutrail
      POSTGRES_PASSWORD: edutrail-db-pw
      POSTGRES_DB: edutrail
    volumes:
      - ./.containers/edutrail-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"