services:
  edutrail.webui:
    image: ${DOCKER_REGISTRY-}edutrailwebui
    build:
      context: .
      dockerfile: src/EduTrail.WebUI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - EDUTRAIL_ConnectionStrings__DefaultConnection=Host=edutrail.db;Port=5432;Database=edutrail;Username=edutrail;Password=edutrail-db-pw
      # Created on first startup
      #- EDUTRAIL_DefaultAdminUser__Email=admin@example.com
      #- EDUTRAIL_DefaultAdminUser__Password=MyAdminPassword123!
    depends_on: 
      edutrail.db:
        condition: service_healthy

  edutrail.db:
    image: postgres:16
    environment:
      POSTGRES_USER: edutrail
      POSTGRES_PASSWORD: edutrail-db-pw
      POSTGRES_DB: edutrail
    volumes:
      - ./.containers/edutrail-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
