services:
  edutrail.webui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - EDUTRAIL_ConnectionStrings__DefaultConnection=Host=edutrail.db;Port=5432;Database=edutrail;Username=edutrail;Password=edutrail-db-pw
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  edutrail.dev.adminer:
    image: adminer
    restart: always
    depends_on: 
      - edutrail.db
    ports:
      - 8070:8080

  edutrail.dev.seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8071:80"
    volumes:
      - ./.containers/edutrail-seq-logs:/data