name: Push to Artifact Registry

on:
  workflow_dispatch:
  push:
    branches: ["main", "develop"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main", "develop"]

env:
  DOCKERFILE_PATH: 'src/EduTrail.WebUI/Dockerfile'
  IMAGE_NAME: '${{ github.event.repository.name }}'

  PROJECT_ID: '${{ vars.GCR_PROJECT_ID }}'
  REGISTRY: '${{ vars.GCAR_REPO_LOCATION }}-docker.pkg.dev' # 'europe-west1-docker.pkg.dev'
  AR_URL: '${{ vars.GCAR_REPO_LOCATION }}-docker.pkg.dev/${{ vars.GCR_PROJECT_ID }}/${{ vars.GCR_SERVICE_NAME }}'
  SERVICE_ACCOUNT: '${{ secrets.GCWIF_SERVICE_ACCOUNT }}' # 'github-actions-service-account@my-project-id.iam.gserviceaccount.com'
  WORKLOAD_IDENTITY_PROVIDER: '${{ secrets.GCWIF_PROVIDER }}' # 'projects/123456789/locations/global/workloadIdentityPools/my-app-dev-pool/providers/github-actions-provider'

jobs:
  build-test:
    uses: .github/workflows/test.yml

  push-to-ar:
    needs: ['build-test']
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: 'actions/checkout@v4'

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          project_id: '${{ env.PROJECT_ID }}'
          service_account: '${{ env.SERVICE_ACCOUNT }}'
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      - name: Docker meta
        id: meta
        uses: 'docker/metadata-action@v5'
        with:
          images: '${{ env.IMAGE_NAME }}'

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.REGISTRY }}'

      - name: Build and Push Container
        run: |-
          DOCKER_TAG="${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -f "${{ env.DOCKERFILE_PATH }}" -t "${DOCKER_TAG}" ./
          docker push "${DOCKER_TAG}"
          echo "DOCKER_TAG=${DOCKER_TAG}" >> "$GITHUB_ENV"

#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          push: ${{ github.event_name != 'pull_request' }}
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
