name: .NET Tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: ["main", "develop"]
    paths: ["src/**", "tests/**"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Cache NuGet
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}

      - name: Restore dependencies
        run: dotnet restore EduTrail.sln
      - name: Build
        run: dotnet build EduTrail.sln --configuration Release --no-restore
      - name: Run tests
        run: dotnet test EduTrail.sln --configuration Release --no-build --verbosity normal
